### ISSUE TITLE
章节分文件保存

### ISSUE THREAD

**Issue by iydon** [xjtu-blacksmith/notes-on-computing-methods#1]
注意到 `main.text` 有 2317 行, 或许可以考虑将不同章节分文件保存, 归放于 `chapters` 文件夹底下, 方便出错的调试与修改.
此外, 2018 年我上数值分析也整理过一份[笔记](https://github.com/Iydon/Numerical_Analysis_Notes), 但感觉你的内容更丰富, 不过我使用程序实现作业中及课本中使用的算法, 或许可以参考一下, 如果有兴趣可以完善你的文档.

**Comment by xjtu-blacksmith** [comment]
- 文档初开始撰写时，未注意分文件保存，之后就一直写在一个文档里。您的建议很好，我会来处理这一问题。
- 关于算法的问题，我之前有考虑过，总体的感觉是应该单独整理成一份与课程笔记（或课本）独立的资料，呈现形式也最好是在线的 REPL，或至少是有代码高亮的 Markdown 文档，方便他人调试与copy。近来忙于其它一些事情，待我有空后了解一下您目前的工作状况后，再与您讨论此事。

**Comment by iydon** [comment]
嗯嗯

**Comment by xjtu-blacksmith** [comment]
- 分章节问题已解决，体现在 v1.1 版本中。
- 程序、算法问等，本人暂无精力考虑。下学期时有一些同学要上此课，我会向他们提出此方面的建议。
