### ISSUE TITLE
错误修正

### ISSUE THREAD

**Issue by ilcpm** [xjtu-blacksmith/notes-on-computing-methods#2]
PDF总第26页存在一个错误

![image](https://user-images.githubusercontent.com/36830343/84882313-9e588700-b0c1-11ea-8bf1-5ea6de8fca44.png)

如图所示，拉格朗日插值法中，图中划出的“分母”，应为“分子”，望修正

另外“故只需计算插值基函数的**系数**”这句话，可以修改为“只需计算插值基函数的**分母**”便于理解

**Comment by xjtu-blacksmith** [comment]
已在源代码中更正，PDF 文件待日发布。感谢指正！
