### ISSUE TITLE
您好,我想使用一下你们修改的模板进行我们自己的课程笔记的使用,想要征求一下你们的同意

### ISSUE THREAD

**Issue by MoonTracer732** [xjtu-blacksmith/notes-on-computing-methods#3]

**Comment by xjtu-blacksmith** [comment]
本笔记使用 [qyxf-book](https://github.com/qyxf/qyxf-book) 模板制作，具体的移用细则请参见 [LICENSE](https://github.com/xjtu-blacksmith/notes-on-computing-methods/blob/master/LICENSE)。简单来说：如果你们只是将模板作为作品的一部分附带发布，只需将此 LICENSE 文件一同附带在源代码中，并在适当位置（如 README）说明所用模板的来源即可。

**Comment by MoonTracer732** [comment]
好的，谢谢，因为您对原有书籍的形式进行了修改，在原有书籍模版的形式基础上我还要进行一些自己的修改，故在这里征求一下您的同意，我会按照以上的移用细则进行迁移的，同时会在这些部分标注您的贡献，谢谢
